apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  labels:
    {{- include "accounts-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres;Port={{ .Values.postgres.service.port }};Database={{ .Values.postgres.database }};Username={{ .Values.postgres.username }};Password={{ .Values.postgres.password }}"
