apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    {{- include "accounts-api.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.api.env.aspnetcoreEnvironment | quote }}
  ASPNETCORE_URLS: "http://+:{{ .Values.api.containerPort }}"
