apiVersion: v1
kind: Service
metadata:
  name: accounts-api
  labels:
    {{- include "accounts-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: accounts-api
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.containerPort }}
      {{- if eq .Values.api.service.type "NodePort" }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
