apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts-api.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "accounts-api.labels" . | nindent 4 }}
data:
  APPLICATION_NAME: {{ .Values.appName | quote }}
  ASPNETCORE_ENVIRONMENT: {{ .Values.aspnetEnvironment | quote }}
  Seq__ServerUrl: {{ .Values.seq.serverUrl | quote }}
