apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounts-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "accounts-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host={{ .Values.postgres.host }};Port={{ .Values.postgres.port }};Database={{ .Values.postgres.database }};Username={{ .Values.postgres.username }};Password={{ .Values.postgres.password }}"
