apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: accounts
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=accountsdb;Username=postgres;Password=postgres"
