apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-api
  namespace: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts-api
  template:
    metadata:
      labels:
        app: accounts-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16
          command:
            - sh
            - -c
            - >
              until pg_isready -h postgres -p 5432 -U postgres; do
                echo waiting for postgres...;
                sleep 2;
              done
      containers:
        - name: accounts-api
          image: docker.io/19942709/accounts-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /api/accounts
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/accounts
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
