replicaCount: 2

nameOverride: ""
fullnameOverride: ""

image:
  repository: docker.io/katty0055/accounts-api
  tag: latest
  pullPolicy: Always

containerPort: 8080

# Datos no sensibles -> ConfigMap
appName: CleanArchitecture.Full.Api
aspnetEnvironment: Development

# Centralización de logs -> Seq (service interno del clúster)
seq:
  serverUrl: http://seq

# Datos de conexión a la base -> Secret (se arma la connection string en el template)
postgres:
  host: postgres
  port: 5432
  database: accountsdb
  username: postgres
  password: postgres

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30080

# Init container que espera a que Postgres esté listo antes de arrancar la API
waitForPostgres:
  enabled: true
  image: postgres:16

probes:
  path: /api/v1/accounts
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
  liveness:
    initialDelaySeconds: 20
    periodSeconds: 15

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
